import = [
    "~/.config/alacritty/themes/nightfox.toml",
    # "~/.config/alacritty/themes/nordfox.toml",
    # "~/.config/alacritty/themes/dayfox.toml",
]

[font]
normal = { family = "UbuntuSansMono Nerd Font", style = "Regular" }
bold = { family = "UbuntuSansMono Nerd Font", style = "Medium" }
italic = { family = "UbuntuSansMono Nerd Font", style = "Regular" }


[window]
opacity = 0.9
decorations = "Buttonless"
startup_mode = "SimpleFullscreen"
# Mac
# startup_mode = "Fullscreen"

