import = [
    "./nightfox.toml"
    # "./dayfox.toml"
]

[font]
normal = { family = "UbuntuSansMono Nerd Font", style = "Regular" }
bold = { family = "UbuntuSansMono Nerd Font", style = "Medium" }
italic = { family = "UbuntuSansMono Nerd Font", style = "Regular" }


[window]
# opacity = 0.4
# blur = true
decorations = "Buttonless"
# Mac
startup_mode = "SimpleFullscreen"
# startup_mode = "Fullscreen"

