import = [
    # "~/.config/alacritty/themes/nightfox.toml",
    "~/.config/alacritty/themes/github.toml",
    # "~/.config/alacritty/themes/nordfox.toml",
    # "~/.config/alacritty/themes/dayfox.toml",
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "UbuntuSansMono Nerd Font", style = "Regular" }
bold = { family = "UbuntuSansMono Nerd Font", style = "Bold" }
italic = { family = "UbuntuSansMono Nerd Font", style = "Italic" }
# normal = { family = "DMMono", style = "Medium" }
# bold = { family = "DMMono", style = "Medium" }
# italic = { family = "DMMono", style = "Regular" }

size = 11


[window]
opacity = 0.9
decorations = "Buttonless"
startup_mode = "SimpleFullscreen"
# Mac
# startup_mode = "Fullscreen"

[selection]
save_to_clipboard = true

