import = [
    # "~/.config/alacritty/themes/nightfox.toml",
    # "~/.config/alacritty/themes/art.toml",
    # "~/.config/alacritty/themes/artlight.toml",
    # "~/.config/alacritty/themes/nordfox.toml",
    "~/.config/alacritty/themes/nvimlight.toml",
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "UbuntuSansMono Nerd Font", style = "Regular" }
bold = { family = "UbuntuSansMono Nerd Font", style = "Bold" }
italic = { family = "UbuntuSansMono Nerd Font", style = "Italic" }

size = 11


[window]
# opacity = 0.9
decorations = "Buttonless"
startup_mode = "SimpleFullscreen"
# Mac
# startup_mode = "Fullscreen"

[selection]
save_to_clipboard = true

