import = [
    "~/.config/alacritty/themes/art_kanagawa.toml",
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Mononoki Nerd Font", style = "Regular" }
bold = { family = "Mononoki Nerd Font", style = "Bold" }
italic = { family = "Mononoki Nerd Font", style = "Regular" }

size = 10

[window]
decorations = "Buttonless"
startup_mode = "SimpleFullscreen"

[selection]
save_to_clipboard = true

