[manager]
show_hidden = true
ratio = [1, 3, 4]

[opener]
edit = [
    { run = 'nvim "$@"', block = true, desc = "Nvim" },
    { run = 'sudo nvim "$0"', block = true, desc = "Sudo nvim"},
]

open = [
    { run = 'alacritty --working-directory "$0"', orphan = true, desc = "Alacritty"},
]



